version: 2

project_name: distill

before:
  hooks:
    - go mod tidy

builds:
  - id: distill
    main: .
    binary: distill
    ldflags:
      - -s -w
      - -X github.com/damnhandy/distill/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: distill
    builds: [distill]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

nfpms:
  - id: distill
    package_name: distill
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://github.com/damnhandy/distill"
    maintainer: "Ryan J. McDonough <ryan@damnhandy.com>"
    description: "Build minimal, immutable OCI images from enterprise Linux base distributions"
    license: Apache-2.0
    formats:
      - deb
      - rpm
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/distill/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/distill/README.md

brews:
  - repository:
      owner: damnhandy
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/damnhandy/distill"
    description: "Build minimal, immutable OCI images from enterprise Linux base distributions"
    license: Apache-2.0
    install: |-
      bin.install "distill"
    test: |-
      system "#{bin}/distill", "version"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - id: distill
    artifacts: archive

signs:
  - id: distill
    cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

changelog:
  use: github
  sort: asc
  groups:
    - title: "New features"
      regexp: "^feat"
      order: 0
    - title: "Bug fixes"
      regexp: "^fix"
      order: 1
    - title: "Documentation"
      regexp: "^docs"
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore"
      - "^ci"
      - "^test"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: damnhandy
    name: distill
  prerelease: auto
  draft: false
