#!/usr/bin/env bash
#
# Quality Gate check #3: SBOM completeness.
#
# Cross-checks that every package present in the RPM or dpkg database inside
# the image is represented in the SBOM generated by Syft. An SBOM with gaps
# fails compliance audits — catch it at build time, not in front of an
# auditor.
#
# Usage:
#   sbom-completeness.sh <image-ref> <sbom-file>
#
# The SBOM must be an SPDX JSON file produced by `distill attest` / Syft.

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=./lib.sh
source "$here/lib.sh"

image=${1:?usage: sbom-completeness.sh <image-ref> <sbom-file>}
sbom=${2:?usage: sbom-completeness.sh <image-ref> <sbom-file>}

qg::require jq
cli=$(qg::container_cli)

if ! [[ -f $sbom ]]; then
  qg::fail "SBOM not found: $sbom"
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# ── Extract the in-image package list ──────────────────────────────────────
# Try RPM first (RHEL/UBI/CentOS/Rocky/Alma), then dpkg (Debian/Ubuntu).
# If neither database is present (e.g. runtime variant that removed it), we
# cannot verify completeness. In that case, fall back to the source image's
# DB — the package manager was present there during build.

image_packages=$tmp/image-packages.txt

extract_rpm() {
  "$cli" run --rm --entrypoint /bin/sh "$image" -c 'rpm -qa 2>/dev/null | sort -u' 2>/dev/null
}
extract_dpkg() {
  "$cli" run --rm --entrypoint /bin/sh "$image" -c 'dpkg-query -W -f "${Package}\n" 2>/dev/null | sort -u' 2>/dev/null
}

if out=$(extract_rpm) && [[ -n $out ]]; then
  echo "$out" > "$image_packages"
  db=rpm
elif out=$(extract_dpkg) && [[ -n $out ]]; then
  echo "$out" > "$image_packages"
  db=dpkg
else
  qg::warn "no RPM or dpkg DB accessible in image (expected for runtime variants without a shell) — using Syft catalogers as authoritative"
  db=syft-only
fi

# ── Extract the SBOM package list ─────────────────────────────────────────
# SPDX JSON: .packages[].name
sbom_packages=$tmp/sbom-packages.txt
jq -r '.packages[]?.name // empty' "$sbom" \
  | sort -u \
  > "$sbom_packages"

if [[ ! -s $sbom_packages ]]; then
  qg::fail "SBOM contains no packages — likely malformed"
  exit 1
fi

qg::info "SBOM lists $(wc -l <"$sbom_packages" | tr -d ' ') packages"

if [[ $db == "syft-only" ]]; then
  qg::pass "SBOM non-empty; no in-image DB to cross-check against"
  exit 0
fi

# ── Diff ──────────────────────────────────────────────────────────────────
# Packages in the image DB that are missing from the SBOM.
missing=$tmp/missing.txt
comm -23 "$image_packages" "$sbom_packages" > "$missing"

# On RPM images, package names in the DB include architecture and version
# suffixes (glibc-2.34-83.el9.x86_64) while Syft normalizes to name-only.
# Strip common suffixes and try again before failing.

if [[ -s $missing && $db == "rpm" ]]; then
  normalized=$tmp/image-packages-normalized.txt
  # Strip -<ver>-<rel>.<arch> tail. Heuristic but correct for stock RPMs.
  sed -E 's/-[0-9].*$//' "$image_packages" | sort -u > "$normalized"
  comm -23 "$normalized" "$sbom_packages" > "$missing"
fi

if [[ -s $missing ]]; then
  qg::fail "$(wc -l <"$missing" | tr -d ' ') package(s) in $db DB are missing from SBOM:"
  head -20 "$missing" | sed 's/^/    /' >&2
  if (( $(wc -l <"$missing") > 20 )); then
    echo "    … (truncated)" >&2
  fi
  exit 1
fi

qg::pass "SBOM covers every package in the $db DB"
