package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// basePreset holds the known values for a well-known base distribution.
type basePreset struct {
	Image          string
	Releasever     string
	PackageManager string
	DefaultShell   string
	DefaultCmd     string
	SamplePackages []string
}

// basePresets maps the --base shorthand to a fully resolved preset.
var basePresets = map[string]basePreset{
	"ubi9": {
		Image:          "registry.access.redhat.com/ubi9/ubi",
		Releasever:     "9",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"ubi8": {
		Image:          "registry.access.redhat.com/ubi8/ubi",
		Releasever:     "8",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"fedora": {
		Image:          "registry.fedoraproject.org/fedora:latest",
		Releasever:     "41",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"debian": {
		Image:          "debian:bookworm-slim",
		Releasever:     "bookworm",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
	"ubuntu": {
		Image:          "ubuntu:24.04",
		Releasever:     "noble",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
	"ubuntu22": {
		Image:          "ubuntu:22.04",
		Releasever:     "jammy",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
}

var initTemplate = template.Must(template.New("distill").Parse(`# Generated by distill init
# See: https://github.com/damnhandy/distill

name: {{ .Name }}
description: ""

# variant controls whether the package manager is removed from the final image.
# "runtime" removes it (default); "dev" retains it for development images.
variant: {{ .Variant }}

# tags are the OCI image references applied to the built image.
# Equivalent to passing -t to docker/podman build.
{{- if .Tag }}
tags:
  - {{ .Tag }}
{{- else }}
# tags:
#   - myregistry.io/{{ .Name }}:latest
{{- end }}

# platforms lists the target build platforms. Defaults to [linux/amd64, linux/arm64].
platforms:
  - linux/amd64
  - linux/arm64

base:
  image: {{ .Image }}
  releasever: "{{ .Releasever }}"
  # packageManager is auto-inferred from the base image; set explicitly to override.
  # packageManager: {{ .PackageManager }}

contents:
  packages:
{{- range .SamplePackages }}
    - {{ . }}
{{- end }}
    # Add more packages here.

# accounts defines non-root users and groups to create inside the image.
accounts:
  run-as: appuser
  users:
    - name: appuser
      uid: 10001
      gid: 10001
      shell: {{ .DefaultShell }}
  groups:
    - name: appuser
      gid: 10001

# environment variables set in the final image (ENV in Dockerfile).
environment:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

# cmd is the default command when the container is run.
cmd:
  - {{ .DefaultCmd }}

# Uncomment to set a custom entrypoint.
# entrypoint:
#   - /docker-entrypoint.sh

# Uncomment to set the working directory inside the container.
# work-dir: /app

# annotations are OCI image metadata labels.
# annotations:
#   org.opencontainers.image.source: https://github.com/example/myapp

# volumes declares mount points (VOLUME in Dockerfile).
# volumes:
#   - /data

# ports declares exposed network ports (EXPOSE in Dockerfile).
# ports:
#   - "8080/tcp"

# paths declares filesystem entries to create in the image chroot.
# paths:
#   - type: directory
#     path: /app
#     uid: 10001
#     gid: 10001
#     mode: "0755"
`))

func newInitCmd() *cobra.Command {
	var (
		name    string
		base    string
		variant string
		output  string
		tag     string
		force   bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a new .distill.yaml spec file",
		Long: `init generates a .distill.yaml scaffold with sensible defaults for
the chosen base distribution.

Known base values:
  ubi9      — Red Hat UBI 9 (DNF)
  ubi8      — Red Hat UBI 8 (DNF)
  fedora    — Fedora latest (DNF)
  debian    — Debian Bookworm slim (APT)
  ubuntu    — Ubuntu 24.04 LTS (APT)
  ubuntu22  — Ubuntu 22.04 LTS (APT)

When --base is omitted a generic template with placeholder values is written.`,
		Example: `  distill init --base ubi9 --name myapp
  distill init --base debian --name myservice --tag myregistry.io/myservice:latest
  distill init --base ubi9 --variant dev --output dev.distill.yaml`,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runInit(name, base, variant, output, tag, force)
		},
	}

	cmd.Flags().StringVarP(&name, "name", "n", "", "Image name (default: current directory name)")
	cmd.Flags().StringVarP(&base, "base", "b", "",
		"Base distribution (ubi9, ubi8, fedora, debian, ubuntu, ubuntu22)")
	cmd.Flags().StringVarP(&variant, "variant", "v", "runtime",
		`Image variant: "runtime" removes the package manager; "dev" retains it`)
	cmd.Flags().StringVarP(&output, "output", "o", "image.distill.yaml", "Output file path")
	cmd.Flags().StringVarP(&tag, "tag", "t", "", "Initial image tag (e.g. myregistry.io/myapp:latest)")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "Overwrite existing file")

	return cmd
}

func runInit(name, base, variant, output, tag string, force bool) error {
	if variant != "runtime" && variant != "dev" {
		return fmt.Errorf("variant must be \"runtime\" or \"dev\", got %q", variant)
	}

	// Resolve name from the current directory when not provided.
	if name == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getting working directory: %w", err)
		}
		name = filepath.Base(cwd)
		name = strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
				return r
			}
			if r >= 'A' && r <= 'Z' {
				return r + 32 // to lower
			}
			return '-'
		}, name)
	}

	// Resolve base preset or use generic placeholder values.
	var (
		image          = "YOUR_BASE_IMAGE"
		releasever     = "VERSION"
		packageManager = "dnf"
		defaultShell   = "/sbin/nologin"
		defaultCmd     = "/bin/sh"
		samplePackages = []string{"# add packages here"}
	)
	if base != "" {
		p, ok := basePresets[base]
		if !ok {
			keys := make([]string, 0, len(basePresets))
			for k := range basePresets {
				keys = append(keys, k)
			}
			return fmt.Errorf("unknown base %q — choose from: %s", base, strings.Join(keys, ", "))
		}
		image = p.Image
		releasever = p.Releasever
		packageManager = p.PackageManager
		defaultShell = p.DefaultShell
		defaultCmd = p.DefaultCmd
		samplePackages = p.SamplePackages
	}

	// Check for existing file.
	if !force {
		if _, err := os.Stat(output); err == nil {
			return fmt.Errorf("%s already exists — use --force to overwrite", output)
		}
	}

	f, err := os.OpenFile(output, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600) //nolint:gosec // G304: output is provided by the operator
	if err != nil {
		return fmt.Errorf("creating %s: %w", output, err)
	}
	if err := initTemplate.Execute(f, map[string]any{
		"Name":           name,
		"Variant":        variant,
		"Tag":            tag,
		"Image":          image,
		"Releasever":     releasever,
		"PackageManager": packageManager,
		"DefaultShell":   defaultShell,
		"DefaultCmd":     defaultCmd,
		"SamplePackages": samplePackages,
	}); err != nil {
		_ = f.Close()
		return fmt.Errorf("rendering template: %w", err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("writing %s: %w", output, err)
	}

	fmt.Printf("Created %s\n", output)
	if base == "" {
		fmt.Println("Edit the file and replace placeholder values before running distill build.")
	}
	return nil
}
