package spec

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// BasePreset holds the default values for a well-known base distribution.
type BasePreset struct {
	Image          string
	Releasever     string
	PackageManager string
	DefaultShell   string
	DefaultCmd     string
	SamplePackages []string
}

// BasePresets maps --base shorthand keys to fully resolved presets.
var BasePresets = map[string]BasePreset{
	"ubi9": {
		Image:          "registry.access.redhat.com/ubi9/ubi",
		Releasever:     "9",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"ubi8": {
		Image:          "registry.access.redhat.com/ubi8/ubi",
		Releasever:     "8",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"fedora": {
		Image:          "registry.fedoraproject.org/fedora:latest",
		Releasever:     "41",
		PackageManager: "dnf",
		DefaultShell:   "/sbin/nologin",
		DefaultCmd:     "/bin/bash",
		SamplePackages: []string{"glibc", "ca-certificates"},
	},
	"debian": {
		Image:          "debian:bookworm-slim",
		Releasever:     "bookworm",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
	"ubuntu": {
		Image:          "ubuntu:24.04",
		Releasever:     "noble",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
	"ubuntu22": {
		Image:          "ubuntu:22.04",
		Releasever:     "jammy",
		PackageManager: "apt",
		DefaultShell:   "/usr/sbin/nologin",
		DefaultCmd:     "/bin/sh",
		SamplePackages: []string{"libc6", "ca-certificates"},
	},
}

var scaffoldTemplate = template.Must(template.New("distill").Parse(`# Generated by distill init
# See: https://github.com/damnhandy/distill

name: {{ .Name }}
description: ""

# variant controls whether the package manager is removed from the final image.
# "runtime" removes it (default); "dev" retains it for development images.
variant: {{ .Variant }}

# platforms lists the target build platforms. Defaults to [linux/amd64, linux/arm64].
platforms:
  - linux/amd64
  - linux/arm64

# source is the distribution image used for the chroot bootstrap.
source:
  image: {{ .Image }}
  releasever: "{{ .Releasever }}"
  # packageManager is auto-inferred from the source image; set explicitly to override.
  # packageManager: {{ .PackageManager }}

# destination is the OCI image reference applied to the built image.
{{- if .DestinationImage }}
destination:
  image: {{ .DestinationImage }}
{{- if .DestinationTag }}
  releasever: {{ .DestinationTag }}
{{- end }}
{{- else }}
# destination:
#   image: myregistry.io/{{ .Name }}
#   releasever: latest
{{- end }}

contents:
  packages:
{{- range .SamplePackages }}
    - {{ . }}
{{- end }}
    # Add more packages here.

# accounts defines non-root users and groups to create inside the image.
accounts:
  run-as: appuser
  users:
    - name: appuser
      uid: 10001
      gid: 10001
      shell: {{ .DefaultShell }}
  groups:
    - name: appuser
      gid: 10001

# environment variables set in the final image (ENV in Dockerfile).
environment:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

# cmd is the default command when the container is run.
cmd:
  - {{ .DefaultCmd }}

# Uncomment to set a custom entrypoint.
# entrypoint:
#   - /docker-entrypoint.sh

# Uncomment to set the working directory inside the container.
# work-dir: /app

# annotations are OCI image metadata labels.
# annotations:
#   org.opencontainers.image.source: https://github.com/example/myapp

# volumes declares mount points (VOLUME in Dockerfile).
# volumes:
#   - /data

# ports declares exposed network ports (EXPOSE in Dockerfile).
# ports:
#   - "8080/tcp"

# paths declares filesystem entries to create in the image chroot.
# paths:
#   - type: directory
#     path: /app
#     uid: 10001
#     gid: 10001
#     mode: "0755"

# pipeline declares supply-chain steps that run after distill build --pipeline
# or distill publish. Remove the comment markers to enable individual steps.
# pipeline:
#   scan:
#     enabled: true
#     fail-on: critical
#   sbom:
#     enabled: true
#   provenance:
#     enabled: true
`))

// ScaffoldSpec generates a .distill.yaml YAML string for the given parameters.
// base may be a shorthand key (ubi9, debian, etc.) or a fully qualified image URI.
// variant must be "runtime" or "dev". destination is an optional OCI reference
// (e.g. "myregistry.io/myapp:latest"). Returns an error for unknown shorthands.
func ScaffoldSpec(name, base, variant, destination string) (string, error) {
	var (
		image          = "YOUR_BASE_IMAGE"
		releasever     = "VERSION"
		packageManager = "dnf"
		defaultShell   = "/sbin/nologin"
		defaultCmd     = "/bin/sh"
		samplePackages = []string{"# add packages here"}
	)

	if base != "" {
		if p, ok := BasePresets[base]; ok {
			image = p.Image
			releasever = p.Releasever
			packageManager = p.PackageManager
			defaultShell = p.DefaultShell
			defaultCmd = p.DefaultCmd
			samplePackages = p.SamplePackages
		} else if strings.ContainsAny(base, "/:") {
			// Fully qualified image URI — infer the package manager.
			image = base
			releasever = "VERSION"
			packageManager = InferPackageManager(base)
			if packageManager == "apt" {
				defaultShell = "/usr/sbin/nologin"
				defaultCmd = "/bin/sh"
				samplePackages = []string{"libc6", "ca-certificates"}
			} else {
				defaultShell = "/sbin/nologin"
				defaultCmd = "/bin/bash"
				samplePackages = []string{"glibc", "ca-certificates"}
			}
		} else {
			keys := make([]string, 0, len(BasePresets))
			for k := range BasePresets {
				keys = append(keys, k)
			}
			return "", fmt.Errorf("unknown base %q — use a shorthand key (%s) or a fully qualified image URI",
				base, strings.Join(keys, ", "))
		}
	}

	destImage, destTag := SplitDestination(destination)

	var buf bytes.Buffer
	if err := scaffoldTemplate.Execute(&buf, map[string]any{
		"Name":             name,
		"Variant":          variant,
		"DestinationImage": destImage,
		"DestinationTag":   destTag,
		"Image":            image,
		"Releasever":       releasever,
		"PackageManager":   packageManager,
		"DefaultShell":     defaultShell,
		"DefaultCmd":       defaultCmd,
		"SamplePackages":   samplePackages,
	}); err != nil {
		return "", fmt.Errorf("rendering spec template: %w", err)
	}
	return buf.String(), nil
}

// SplitDestination splits a full OCI reference (e.g. "myregistry.io/myapp:latest")
// into the image name and tag parts. If no tag is present the tag is returned empty.
func SplitDestination(ref string) (image, tag string) {
	if ref == "" {
		return "", ""
	}
	// Find the last colon that appears after the last slash (to avoid splitting
	// on the port in a registry URL like myregistry.io:5000/myapp).
	lastSlash := strings.LastIndex(ref, "/")
	lastColon := strings.LastIndex(ref, ":")
	if lastColon > lastSlash {
		return ref[:lastColon], ref[lastColon+1:]
	}
	return ref, ""
}
